# Generated by Django 5.0.3 on 2024-03-23 17:03

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.SmallIntegerField()),
                ('rank', models.SmallIntegerField()),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=models.SET(employees.models.delete_employees), to='employees.employee')),
            ],
        ),
    ]
